name: Node.js push on tag

on:
  pull_request:
    branches: [develop]

env:
  DOCKER_ORGANIZATION: s652
  DOCKER_REPOSITORY: frontend-service
  KUBERNETES_NAMESPACE: s65-2
  WEBSITE_URL: https://delegate-market.nl

jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: K6Scripts/test.js
          cloud: true
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_API_TOKEN }}