name: Node.json push on every branch

on:
  push:
    branches:
      - "*"         # matches every branch
      - "*/*"       # matches every branch containing a single '/'
      - "!master"
      - "!develop"

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true