name: Node.js CI

on: [push]
#  push:
#    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true