name: Node.js pull_request on develop branch

on:
  pull_request: 
    branches: [develop]
    
env:
  DOCKER_ORGANIZATION: s652
  DOCKER_REPOSITORY: frontend-service

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: node:12.16.2
    
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Decrypt the GPG encrypted config files
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.GPG_PASSPHRASE }} --output ./src/config.json --decrypt ./src/config.json.gpg

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build --if-present
      
      # Test the project
      - name: Test
        run: npm test
        env:
          CI: true

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_ACCESS_TOKEN }}

  k6:
    runs-on: ubuntu-18.04
    steps:
      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: test.js
          cloud: true
          token: ${{ secrets.K6_API_TOKEN }}

  lighthouse:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create /tmp/lighthouse-report directory
        run: mkdir /tmp/lighthouse-report
      
      - name: Run Lighthouse check
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/lighthouse-report
          urls: http://34.120.162.205

      - name: Upload Lighthouse report artifact
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-report-artifact
          path: /tmp/lighthouse-report